-- Beyond Shape — Phase D Slice 1: `contributions` (DR-1, DR-3 append-only).
-- The living archive: a visitor's reading given into the crowd. DR-2 ruling:
-- store the sentence too, published as a CC BY-SA collective artwork.
--
-- DR-3 append-only: this schema has NO UPDATE/DELETE path — rows are INSERTed
-- once and never rewritten. (Consented deletion is a documented FUTURE path,
-- not built here — see the README notes.)

CREATE TABLE IF NOT EXISTS contributions (
  id TEXT PRIMARY KEY,                       -- uuid v4 (generated by the function)
  created_at INTEGER NOT NULL,               -- ms epoch
  contributor_anon_id TEXT NOT NULL,         -- device-pseudonymous, no account (DR-1)
  input_text TEXT NOT NULL,                  -- the sentence (DR-2 ruling: stored)
  text_sha256 TEXT NOT NULL,                 -- integrity of the stored text (DR-2)
  form_params TEXT NOT NULL,                 -- JSON: the accepted rendered SdfParams
  z TEXT NOT NULL,                           -- JSON: the latent (reproducibility)
  drift REAL NOT NULL,                       -- the shaping knob
  seed INTEGER NOT NULL,                     -- the shaping seed
  gradient TEXT NOT NULL CHECK (gradient IN ('accept','adjust','reject')),
  consent_flag INTEGER NOT NULL CHECK (consent_flag IN (0,1)),
  fingerprint TEXT NOT NULL,                 -- sha256(text|drift|seed) — FR-10 trace
  register TEXT NOT NULL,                    -- the register the form wore
  blend_mode TEXT NOT NULL,                  -- the decoded surface mode
  tune TEXT                                  -- JSON: the visitor's hand (FR-16) — the delta
                                             -- from the machine's proposal to the tuned form
);

-- For aggregation ("state of the consensus", FR-23) — NOT unique: append-only
-- permits the same sentence reaching the crowd more than once.
CREATE INDEX IF NOT EXISTS idx_contrib_text_sha ON contributions(text_sha256);
CREATE INDEX IF NOT EXISTS idx_contrib_created ON contributions(created_at);
CREATE INDEX IF NOT EXISTS idx_contrib_gradient ON contributions(gradient);
