/**
 * Sensory feature head — v0 stub (spec §3.2).
 *
 * A linear 384 → 16 head clamped to [0,1]: the machine's *features*, not felt
 * experience. The stub performs its stubness: channel *names* live in the
 * manifest (naming is data), labels are provisional — "our words for this, for
 * now" — and the head is regenerated by scripts/train_generator.py alongside
 * the generator (AMEND-4). True sensory "addition" over the embedding is owned
 * by the Slice 2 trained probes (R-a); FR-3(b) reads this as a wiring/sensitivity
 * check, not a novelty proof. Skeleton path: lazy ONNX session, no fetch.
 */

import type { ModelManifest } from '../types';
import { ModelMissingError, SENSORY_CHANNEL_COUNT } from '../types';
import { LazySession, requireModelFile, sensoryChannels } from './models';
import * as ort from 'onnxruntime-web';

export class SensoryHead {
  private readonly session: LazySession<ort.InferenceSession>;
  private readonly manifestRef: ModelManifest;

  constructor(manifest: ModelManifest) {
    this.manifestRef = manifest;
    this.session = new LazySession<ort.InferenceSession>(() => this.createSession());
  }

  private createSession(): Promise<ort.InferenceSession> {
    // requireModelFile throws ModelMissingError when the artifact is absent.
    const file = requireModelFile(this.manifestRef.artifacts.sensory, 'sensory');
    return ort.InferenceSession.create(file, {
      executionProviders: ['webgpu', 'wasm'],
    });
  }

  /** Channel names as data — used to label the v0 vector visibly-provisional. */
  channelNames(): string[] {
    return sensoryChannels(this.manifestRef).map((c) => c.name);
  }

  /**
   * e (384-d) → q (16-d) in [0,1]. The v0 head is a linear probe; if the
   * artifact is missing the load path raises ModelMissingError.
   */
  async forward(e: Float32Array): Promise<Float32Array> {
    const session = await this.session.get().catch((err: unknown) => {
      if (err instanceof ModelMissingError) throw err;
      throw new ModelMissingError('sensory', `sensory session failed: ${(err as Error).message}`);
    });
    const input = new ort.Tensor('float32', new Float32Array(e), [1, e.length]);
    const output = await session.run({ e: input }); // exported input name is "e"
    const raw = (output[session.outputNames[0]!] as ort.Tensor).data as Float32Array;
    const q = new Float32Array(SENSORY_CHANNEL_COUNT);
    for (let i = 0; i < SENSORY_CHANNEL_COUNT; i += 1) {
      const v = raw[i] ?? 0;
      q[i] = Number.isFinite(v) ? Math.min(1, Math.max(0, v)) : 0;
    }
    return q;
  }
}