/**
 * Slice 1 shared types — copied VERBATIM from implementation-spec-slice1 §4
 * (do not rename fields), plus the two additions the slice requires:
 * `ModelMissingError` (loader error contract) and `SensoryChannels`
 * (derived from the manifest: naming is data, not code — FR-3/C1).
 */

export type RunId = string; // uuid v4

/** One completed run, in-browser only (CR-6). Mirrored to sessionStorage `bs:lastRun`. */
export interface RunRecord {
  id: RunId;
  inputText: string;
  e: Float32Array; // 384
  q: Float32Array; // 16, [0,1]  (sensory conditioning vector)
  z: Float32Array; // 64 primary
  zAlternates: Float32Array[]; // 3 more (FR-9)
  sdfParams: SdfParams;
  renderState: RenderStateWire;
  drift: number; // 0..1
  seed: number; // integer
  fingerprint: string; // sha256(text|drift|seed)
  createdAt: number;
  webgl: boolean; // true = Three.js path, false = Canvas-2D fallback
}

export interface SdfParams {
  weights: number[]; // 8 softmax smooth-min weights
  blendRadius: number; // 0.05..0.5
  /** Surface mode of this reading: 'soft' (FR-7 smooth morph) or 'cut' (the
   *  original's overlapping solids). A DECODED variable (0.2.1): an arbitrary
   *  per-anchor convention, never semantic. Absent = legacy/0.2.0 reads,
   *  resolved to 'soft' at decode. */
  blendMode?: 'soft' | 'cut';
  parts: {
    scale: [number, number, number];
    offset: [number, number, number];
    twist: number;
    displacement: number;
  }[]; // len 8
  material: {
    hue: number;
    saturation: number;
    lightness: number;
    roughness: number;
    metalness: number;
    clearcoat: number;
    emissive: number;
  };
  motion: { breathe: number; sway: number }; // 0..1, only when animation toggled on
  pose: { yaw: number; pitch: number; roll: number };
}

export interface RenderStateWire {
  camera: { pos: [number, number, number]; target: [number, number, number] };
  palette: { background: string; key: string; fill: string; rim: string };
}

export interface ModelManifest {
  version: string;
  slice: number;
  generatedAt: string;
  totalBytes: number;
  artifacts: {
    embedder: ManifestEntry;
    tokenizer: ManifestEntry;
    sensory: ManifestEntry;
    denoiser: ManifestEntry;
    decoder: ManifestEntry;
    aligner: ManifestEntry | null;
  };
  sensoryChannels: { name: string }[]; // NAMES IN DATA, not code (FR-3/C1)
  trainingSource?: { seedForms: number; generatedAt: string }; // DR-4 provenance (R-c)
  licenses: string[];
}

export interface ManifestEntry {
  file: string;
  sha256: string;
  sizeBytes: number;
  dim?: number;
  steps?: number;
  maxTokens?: number;
}

export interface SeedForm {
  id: string;
  text: string;
  e: number[];
  zCenter: number[];
  sdfParams: SdfParams;
}

export interface MarginalityNote {
  seed: SeedForm;
  cosE: number;
  cosZ: number;
  differs: boolean;
  note: string;
}

/** Number of sensory conditioning channels (v0 stub, spec §3.2). */
export const SENSORY_CHANNEL_COUNT = 16;

/** Stringify the exact inputs that pin a reading (FR-10/QR-6: sha256 of this). */
export function runSeedMaterial(text: string, drift: number, seed: number): string {
  return `${text}|${drift}|${seed}`;
}

/**
 * The machine reading = one reader among many. `SensoryChannels` is derived
 * from the manifest so channel names can be re-composed as data in later
 * slices without a code change.
 */
export type SensoryChannels = ModelManifest['sensoryChannels'];

/**
 * Raised by any src/core loader when the manifest references an artifact that
 * is not present (scaffold state: the committed manifest points at null files
 * — binaries are regenerated by scripts/train_generator.py).
 */
export class ModelMissingError extends Error {
  readonly artifactKey: string;
  constructor(artifactKey: string, message?: string) {
    super(
      message ??
        `model artifact "${artifactKey}" is not available.\n` +
          'The scaffold ships a manifest without binaries — run ' +
          'scripts/train_generator.py to produce the ONNX artifacts.',
    );
    this.name = 'ModelMissingError';
    this.artifactKey = artifactKey;
  }
}